console.log(" Task 3: GitHub, VS Code & Node.js Setup Steps ");
console.log("1) Create a GitHub Account:");
console.log(" a) Go to: https://github.com/");
console.log(" b) Click on 'Sign up'.");
console.log(" c) Enter your email, password, and username.");
console.log(" d) Verify your email and log in to GitHub.\n");
console.log("2) Create a New GitHub Repository:");
console.log(" a) After login, click the '+' icon in the top-right.");
console.log(" b) Click on 'New repository'.");
console.log(" c) Enter repository name");
console.log(" d) Keep visibility as 'Public' or 'Private' based on preference.");
console.log(" e) Tick 'Add a README file', its optional.");
console.log(" f) Click on 'Create repository'.\n");
console.log("3) Create JavaScript Files in Codespaces:");
console.log(" a) In the left Explorer panel, click 'New File'.");
console.log(" b) Create file: intro.js");
console.log(' c) Add code');
console.log(" d) Save the file.\n");
console.log("4) Running your JavaScript file:");
console.log(" a) Open the terminal in Codespaces.");
console.log(" b) Type: node intro.js");
console.log(" c) If everything is correct, you'll see the output in the terminal.\n");
console.log("5) Saving your work (Commit):");
console.log(" a) Click on the Source Control icon on the left.");
console.log(" b) You'll see the files you changed — click 'Stage All'.");
console.log(" c) Write a message");
console.log(" d) Click Commit to save the changes.\n");
console.log("6) Uploading your code back to GitHub:");
console.log(" a) After committing, click on 'Sync Changes' or 'Push'.");
console.log(" b) Once it's done, your updated files will be visible on GitHub.\n");

console.log("✔ You're all set! Your GitHub, Codespaces, and Node.js setup is finished.");
